open keyword "C:\Users\Naude Conradie\Desktop\Repository\Masters-Project\Models\LSDyna_Unit_Cell_Corner\Steel_Explicit\Unit_Cell_Corner.k"
save keywordoutversion 9
Finished reading model
print png "C:\Users\Naude Conradie\Desktop\Repository\Masters-Project\Presentations\SAIMechE 2019\Unit_Cell_Corner.png" nogamma transparent enlisted "OGL1x1" 
Save Config. parameters to file C:\Users\Naude Conradie\AppData\Roaming\LSTC\LS-PrePost4.6\lsppconf
