| Created by Marc Mentat 2019 (64bit)
*prog_option compatibility:prog_version:ment2019
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\naude conradie\desktop\repository\masters-project\models\marcmentat\units\grid_1_10x10_20x20_2\grid_34_49303fffdc01444dac71fda07d56ecd3\grid_34_49303fffdc01444dac71fda07d56ecd3.mud"
*fill_view
*quit yes
