| Created by Marc Mentat 2019 (64bit)
*prog_option compatibility:prog_version:ment2019
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\naude conradie\desktop\repository\masters-project\models\marcmentat\models\grid_5x5_0\grid_de91e90a15ee4ac6b67dd4588153263b\grid_de91e90a15ee4ac6b67dd4588153263b.mud"
*fill_view
