| Created by Marc Mentat 2019 (64bit)
*prog_option compatibility:prog_version:ment2019
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\naude conradie\desktop\repository\masters-project\models\marcmentat\units\grid_1_10x10_20x20_2\grid_32_73139f4dfe1d218e860bca9c41bc857d\grid_32_73139f4dfe1d218e860bca9c41bc857d.mud"
*fill_view
