| Created by Marc Mentat 2019 (64bit)
*prog_option compatibility:prog_version:ment2019
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\naude conradie\desktop\repository\masters-project\models\marcmentat\units\grid_1_15x15_30x30_2\grid_28_1_33_1_2_27_23\grid_28_1_33_1_2_27_23.mud"
*fill_view
*py_file_run ..\..\..\test.py
