open keyword "C:\Naudé\University\Masters Project\Models\LS-PrePost_Tutorials\2_4_Mesh_ElGen\2_4_Mesh_ElGen\head_and_neck.k"
save keywordoutversion 9
Finished reading model
right
genselect target edge
genselect target segment
genselect target shell
genselect shell add part 1/0 
elgenerate solid shelloffset 3 1207 10 1 
genselect clear
genselect clear
elgenerate accept
elgenerate shelltype 1
genselect target solid
elgenerate shelltype 2
genselect target segment
genselect propagate on
genselect element add solid 1467/F1/0 
genselect element add solid 1315/F1/0 
genselect element add solid 1521/F1/0 
-M 3
+M 3
Nothing picked !
partdata readlist 1 
clearid part
Shell Part #1 
partdata readlist 2 
clearid part
Solid Part #2 
genselect propagate off
partdata readlist 1 
clearid part
Shell Part #1 
partdata readlist 2 
clearid part
Solid Part #2 
partdata readlist 1 
clearid part
Shell Part #1 
partdata readlist 2 
clearid part
Solid Part #2 
partdata readlist 1 
clearid part
Shell Part #1 
partdata readlist 3 
clearid part
Solid Part #3 
-M 3
+M 3
genselect clear
partdata readlist 1  2  3 
clearid part
Shell Part #1 
Solid Part #2 
Solid Part #3 
genselect clear
clearid part
elgenerate shelltype 2
genselect target segment
genselect propagate on
partdata readlist 3 
clearid part
Solid Part #3 
Select solid face first
Select solid face first
clearid part
partdata readlist 3 
clearid part
Solid Part #3 
Select solid face first
-M 1
-M 2
genselect element add solid 1265/F1/0 
genselect element add solid 1419/F1/0 
genselect element add solid 1491/F1/0 
genselect element add solid 1963/F1/0 
genselect element add solid 1963/F1/0 
genselect element add solid 1409/F1/0 
genselect element add solid 1637/F1/0 
genselect element add solid 1390/F1/0 
genselect element add solid 1282/F1/0 
genselect element add solid 1367/F1/0 
genselect element add solid 1459/F1/0 
genselect element add solid 1333/F1/0 
genselect element add solid 1394/F1/0 
genselect element add solid 1455/F1/0 
genselect element add solid 1454/F1/0 
zoomhere -0.101173 0.076705 0.800000;
zoomhere -0.101173 0.076705 1.000000;
zoomhere -0.101173 0.076705 1.250000;
zoomhere -0.101173 0.076705 1.562500;
zoomhere -0.101173 0.076705 1.953125;
zoomhere -0.101173 0.076705 2.441406;
genselect element add solid 1534/F0/0 
quat -0.965045 -0.044358 0.178403 0.186796;
genselect propagate off
genselect element add part 3/0 
front
right
genselect propagate on
genselect element add solid 1329/F1/0 
activelabel clearhilighttag
genselect propagate off
elgenerate shelltype 2
genselect target segment
genselect propagate on
pan -122.696693 123.562614;
zoomhere 0.294721 -0.200284 3.051758;
zoomhere 0.294721 -0.200284 3.814698;
zoomhere 0.294721 -0.200284 3.051758;
zoomhere 0.294721 -0.200284 2.441406;
zoomhere 0.294721 -0.200284 1.953125;
zoomhere 0.294721 -0.200284 1.562500;
genselect element add solid 1464/F1/0 
genselect element add solid 1465/F1/0 
genselect element add solid 1516/F1/0 
genselect element add solid 1521/F1/0 
genselect element add solid 1522/F1/0 
genselect element add solid 1520/F1/0 
genselect element add solid 1515/F1/0 
genselect element add solid 1514/F1/0 
genselect element add solid 1271/F1/0 
genselect element add solid 1299/F1/0 
genselect element add solid 1329/F1/0 
genselect element add solid 1335/F1/0 
genselect element add solid 1277/F1/0 
genselect element add solid 1334/F1/0 
genselect element add solid 1333/F1/0 
genselect element add solid 1394/F1/0 
genselect element add solid 1393/F1/0 
genselect element add solid 1379/F1/0 
genselect element add solid 1963/F1/0 
genselect element add solid 1963/F1/0 
genselect element add solid 1963/F1/0 
genselect element add solid 1972/F1/0 
genselect element add solid 1963/F1/0 
zoomhere 0.085044 -0.313920 1.953125;
zoomhere 0.085044 -0.313920 2.441406;
zoomhere 0.085044 -0.313920 1.953125;
zoomhere 0.085044 -0.313920 1.562500;
zoomhere 0.085044 -0.313920 1.250000;
zoomhere 0.085044 -0.313920 1.000000;
zoomhere 0.085044 -0.313920 0.800000;
zoomhere 0.085044 -0.312500 0.640000;
zoomhere 0.085044 -0.312500 0.512000;
zoomhere 0.085044 -0.312500 0.409600;
genselect element add solid 1728/F4/0 
zoomhere 0.014663 -0.278409 0.327680;
zoomhere 0.014663 -0.278409 0.262144;
zoomhere 0.014663 -0.278409 0.209715;
zoomhere 0.014663 -0.278409 0.262144;
zoomhere 0.017595 -0.278409 0.327680;
zoomhere 0.017595 -0.278409 0.409600;
zoomhere 0.021994 -0.276989 0.512000;
zoomhere 0.021994 -0.276989 0.640000;
zoomhere 0.021994 -0.276989 0.800000;
zoomhere 0.021994 -0.276989 1.000000;
zoomhere 0.021994 -0.276989 1.250000;
zoomhere 0.021994 -0.276989 1.562500;
zoomhere 0.021994 -0.276989 1.953125;
zoomhere -0.140762 -0.311080 1.562500;
zoomhere -0.142229 -0.311080 1.250000;
zoomhere -0.142229 -0.311080 1.000000;
zoomhere -0.142229 -0.311080 0.800000;
zoomhere -0.136364 -0.306818 0.640000;
genselect element add solid 1407/F1/0 
genselect element add solid 1230/F1/0 
genselect element add solid 1406/F1/0 
genselect element add solid 1404/F1/0 
genselect element add solid 1405/F1/0 
genselect element add solid 1478/F1/0 
genselect element add solid 1224/F1/0 
genselect element add solid 1221/F1/0 
genselect element add solid 1815/F1/0 
genselect element add solid 1475/F1/0 
genselect element add solid 1600/F4/0 
genselect element add solid 1901/F1/0 
genselect element add solid 1226/F1/0 
genselect element add solid 1733/F1/0 
genselect element add solid 1411/F1/0 
genselect element add solid 1223/F1/0 
genselect element add solid 1418/F1/0 
genselect element add solid 1430/F1/0 
genselect element add solid 1437/F1/0 
genselect element add solid 1454/F1/0 
pan -67.667625 62.443253;
genselect element add solid 1455/F1/0 
genselect element add solid 1457/F1/0 
genselect element add solid 1439/F1/0 
genselect element add solid 1441/F1/0 
genselect element add solid 1442/F1/0 
genselect element add solid 1444/F1/0 
genselect element add solid 1460/F1/0 
pan -19.127867 112.309174;
genselect element add solid 1387/F1/0 
genselect element add solid 1396/F1/0 
genselect element add solid 1401/F1/0 
genselect element add solid 1388/F1/0 
genselect element add solid 1461/F1/0 
genselect element add solid 1462/F1/0 
genselect element add solid 1389/F1/0 
genselect element add solid 1403/F1/0 
genselect element add solid 1344/F1/0 
genselect element add solid 1340/F1/0 
genselect element add solid 1338/F1/0 
genselect element add solid 1332/F1/0 
genselect element add solid 1302/F1/0 
genselect element add solid 1235/F1/0 
genselect element add solid 1314/F1/0 
pan 57.527832 91.089668;
genselect element add solid 1240/F1/0 
genselect element add solid 1241/F1/0 
genselect element add solid 1236/F1/0 
genselect element add solid 1242/F1/0 
genselect element add solid 1238/F1/0 
genselect element add solid 1468/F1/0 
genselect element add solid 1648/F4/0 
genselect element add solid 1469/F1/0 
genselect element add solid 1237/F1/0 
genselect element add solid 1523/F1/0 
genselect element add solid 1524/F1/0 
genselect element add solid 1518/F1/0 
genselect element add solid 1482/F1/0 
genselect element add solid 1519/F1/0 
genselect element add solid 1525/F1/0 
pan 62.567486 29.287678;
genselect element add solid 1526/F1/0 
genselect element add solid 1527/F1/0 
genselect element add solid 1528/F1/0 
genselect element add solid 1530/F1/0 
top
pan -14.353453 18.943121;
pan -63.688972 17.351654;
zoomhere 0.485337 -0.228693 0.512000;
zoomhere 0.221408 -0.194602 0.409600;
zoomhere 0.221408 -0.194602 0.512000;
zoomhere 0.221408 -0.194602 0.640000;
zoomhere 0.221408 -0.194602 0.800000;
zoomhere 0.221408 -0.194602 1.000000;
genselect element add solid 1537/F1/0 
genselect element add solid 1499/F1/0 
genselect element add solid 1470/F1/0 
genselect element add solid 1354/F1/0 
genselect element add solid 1355/F1/0 
genselect element add solid 1346/F1/0 
genselect element add solid 1365/F1/0 
genselect element add solid 1484/F1/0 
genselect element add solid 1666/F1/0 
genselect element add solid 1639/F1/0 
genselect element add solid 1463/F1/0 
genselect element add solid 1495/F1/0 
genselect element add solid 1347/F1/0 
genselect element add solid 1356/F1/0 
genselect element add solid 1496/F1/0 
genselect element add solid 1497/F1/0 
genselect element add solid 1370/F1/0 
genselect element add solid 1641/F1/0 
genselect element add solid 1962/F1/0 
genselect element add solid 1505/F1/0 
genselect element add solid 1504/F1/0 
genselect element add solid 1498/F1/0 
genselect element add solid 1215/F1/0 
genselect element add solid 1934/F1/0 
genselect element add solid 1231/F1/0 
genselect element add solid 1471/F1/0 
genselect element add solid 1362/F1/0 
genselect element add solid 1474/F1/0 
genselect element add solid 1358/F1/0 
genselect element add solid 1349/F1/0 
genselect element add solid 1212/F1/0 
genselect element add solid 1350/F1/0 
genselect element add solid 1343/F1/0 
genselect element add solid 1214/F1/0 
genselect element add solid 1218/F1/0 
genselect element add solid 1930/F1/0 
genselect element add solid 1481/F1/0 
genselect element add solid 1207/F1/0 
genselect element add solid 1208/F1/0 
genselect element add solid 1663/F1/0 
genselect element add solid 1450/F1/0 
genselect element add solid 1255/F1/0 
genselect element add solid 1262/F1/0 
genselect element add solid 1254/F1/0 
genselect element add solid 1928/F1/0 
genselect element add solid 1926/F1/0 
genselect element add solid 1646/F1/0 
genselect element add solid 1669/F1/0 
genselect element add solid 1938/F1/0 
genselect element add solid 1804/F1/0 
genselect element add solid 1805/F1/0 
genselect element add solid 1796/F1/0 
genselect element add solid 1797/F1/0 
genselect element add solid 1793/F1/0 
genselect element add solid 1792/F1/0 
genselect element add solid 1676/F1/0 
genselect element add solid 1679/F1/0 
genselect element add solid 1643/F1/0 
genselect element add solid 1636/F1/0 
genselect element add solid 1914/F1/0 
genselect element add solid 1942/F1/0 
genselect element add solid 1937/F1/0 
genselect element add solid 1541/F1/0 
genselect element add solid 1961/F1/0 
genselect element add solid 1952/F1/0 
genselect element add solid 1533/F1/0 
genselect element add solid 1628/F1/0 
genselect element add solid 1635/F1/0 
genselect element add solid 1627/F1/0 
genselect element add solid 1306/F1/0 
genselect element add solid 1573/F1/0 
genselect element add solid 1784/F1/0 
genselect element add solid 1634/F1/0 
genselect element add solid 1803/F1/0 
genselect element add solid 1802/F1/0 
genselect element add solid 1658/F1/0 
genselect element add solid 1645/F1/0 
genselect element add solid 1687/F1/0 
genselect element add solid 1944/F1/0 
quat 0.002000 0.008661 0.007165 0.999935;
top
pan -27.765001 27.815529;
genselect element add solid 1575/F1/0 
genselect element add solid 1575/F1/0 
genselect element add solid 1560/F1/0 
genselect element add solid 1560/F1/0 
genselect element add solid 1943/F1/0 
genselect element add solid 1563/F1/0 
genselect element add solid 1700/F1/0 
genselect element add solid 1892/F1/0 
genselect element add solid 1902/F1/0 
genselect element add solid 1809/F1/0 
genselect element add solid 1812/F1/0 
pan -65.065025 26.572195;
genselect element add solid 1591/F1/0 
genselect element add solid 1633/F1/0 
genselect element add solid 1307/F1/0 
genselect element add solid 1591/F1/0 
genselect element add solid 1907/F1/0 
genselect element add solid 1908/F1/0 
genselect element add solid 1813/F1/0 
genselect element add solid 1810/F1/0 
genselect element add solid 1756/F1/0 
bottom
front
pan -20.305040 65.529976;
genselect element add solid 1959/F1/0 
genselect element add solid 1960/F1/0 
genselect element add solid 1506/F1/0 
genselect element add solid 1923/F1/0 
genselect element add solid 1968/F1/0 
genselect element add solid 1283/F1/0 
genselect element add solid 1543/F1/0 
genselect element add solid 1579/F1/0 
genselect element add solid 1567/F1/0 
genselect element add solid 1659/F1/0 
genselect element add solid 1629/F1/0 
genselect element add solid 1308/F1/0 
genselect element add solid 1310/F1/0 
genselect element add solid 1845/F1/0 
genselect element add solid 1561/F1/0 
genselect element add solid 1547/F1/0 
genselect element add solid 1561/F1/0 
genselect element add solid 1665/F1/0 
genselect element add solid 1888/F1/0 
genselect element add solid 1664/F1/0 
genselect element add solid 1662/F1/0 
genselect element add solid 1211/F1/0 
genselect element add solid 1593/F1/0 
genselect element add solid 1311/F1/0 
genselect element add solid 1210/F1/0 
genselect element add solid 1564/F1/0 
genselect element add solid 1562/F1/0 
genselect element add solid 1940/F1/0 
genselect element add solid 1589/F1/0 
genselect element add solid 1843/F1/0 
genselect element add solid 1626/F1/0 
genselect element add solid 1309/F1/0 
genselect element add solid 1312/F1/0 
genselect element add solid 1682/F1/0 
genselect element add solid 1681/F1/0 
genselect element add solid 1604/F1/0 
genselect element add solid 1603/F1/0 
genselect element add solid 1602/F1/0 
genselect element add solid 1601/F1/0 
genselect element add solid 1596/F1/0 
genselect element add solid 1595/F1/0 
genselect element add solid 1592/F1/0 
genselect element add solid 1535/F1/0 
genselect element add solid 1534/F1/0 
genselect element add solid 1590/F1/0 
genselect element add solid 1584/F1/0 
genselect element add solid 1531/F1/0 
genselect element add solid 1532/F1/0 
genselect element add solid 1555/F1/0 
genselect element add solid 1749/F1/0 
genselect element add solid 1897/F1/0 
genselect element add solid 1583/F1/0 
genselect element add solid 1932/F1/0 
genselect element add solid 1929/F1/0 
genselect element add solid 1578/F1/0 
genselect element add solid 1667/F1/0 
genselect element add solid 1582/F1/0 
genselect element add solid 1546/F1/0 
genselect element add solid 1382/F1/0 
genselect element add solid 1500/F1/0 
genselect element add solid 1380/F1/0 
genselect element add solid 1376/F1/0 
genselect element add solid 1548/F1/0 
genselect element add solid 1624/F1/0 
genselect element add solid 1371/F1/0 
genselect element add solid 1374/F1/0 
genselect element add solid 1538/F1/0 
genselect element add solid 1612/F1/0 
genselect element add solid 1249/F1/0 
genselect element add solid 1614/F1/0 
genselect element add solid 1615/F1/0 
genselect element add solid 1895/F1/0 
genselect element add solid 1852/F1/0 
genselect element add solid 1507/F1/0 
genselect element add solid 1958/F1/0 
genselect element add solid 1957/F1/0 
genselect element add solid 1954/F1/0 
genselect element add solid 1956/F1/0 
genselect element add solid 1953/F1/0 
genselect element add solid 1951/F1/0 
genselect element add solid 1632/F1/0 
genselect element add solid 1483/F1/0 
genselect element add solid 1216/F1/0 
genselect element add solid 1219/F1/0 
genselect element add solid 1726/F1/0 
genselect element add solid 1410/F1/0 
genselect element add solid 1950/F1/0 
genselect element add solid 1949/F1/0 
genselect element add solid 1947/F1/0 
genselect element add solid 1946/F1/0 
back
genselect element add solid 1480/F1/0 
genselect element add solid 1670/F1/0 
genselect element add solid 1672/F1/0 
genselect element add solid 1754/F1/0 
pan -20.305040 65.529976;
pan -26.936152 -2.853406;
zoomhere 0.127566 -0.264205 0.800000;
zoomhere 0.127566 -0.264205 0.640000;
zoomhere 0.126100 -0.264205 0.512000;
genselect element add solid 1225/F1/0 
genselect element add solid 1228/F1/0 
genselect element add solid 1917/F1/0 
genselect element add solid 1620/F1/0 
genselect element add solid 1511/F1/0 
genselect element add solid 1509/F1/0 
genselect element add solid 1510/F1/0 
genselect element add solid 1710/F1/0 
genselect element add solid 1559/F1/0 
genselect element add solid 1550/F1/0 
genselect element add solid 1763/F1/0 
genselect element add solid 1734/F1/0 
genselect element add solid 1730/F1/0 
genselect element add solid 1493/F1/0 
pan -33.583839 -19.888783;
genselect element add solid 1755/F1/0 
genselect element add solid 1753/F1/0 
genselect element add solid 1915/F1/0 
genselect element add solid 1545/F1/0 
genselect element add solid 1919/F1/0 
genselect element add solid 1925/F1/0 
genselect element add solid 1588/F1/0 
genselect element add solid 1746/F1/0 
genselect element add solid 1745/F1/0 
genselect element add solid 1744/F1/0 
genselect element add solid 1671/F1/0 
genselect element add solid 1479/F1/0 
genselect element add solid 1415/F1/0 
genselect element add solid 1551/F1/0 
genselect element add solid 1649/F1/0 
genselect element add solid 1623/F1/0 
genselect element add solid 1621/F1/0 
genselect element add solid 1622/F1/0 
genselect element add solid 1920/F1/0 
genselect element add solid 1927/F1/0 
genselect element add solid 1549/F1/0 
pan -18.517933 10.879593;
genselect element add solid 1413/F1/0 
genselect element add solid 1373/F1/0 
genselect element add solid 1422/F1/0 
genselect element add solid 1485/F1/0 
genselect element add solid 1473/F1/0 
genselect element add solid 1677/F1/0 
genselect element add solid 1391/F1/0 
genselect element add solid 1769/F1/0 
genselect element add solid 1738/F1/0 
genselect element add solid 1656/F1/0 
genselect element add solid 1835/F1/0 
genselect element add solid 1741/F1/0 
center 6.148491 -10.542253 -38.576385
pan -22.617182 59.838928;
genselect element add solid 1536/F1/0 
genselect element add solid 1945/F1/0 
genselect element add solid 1580/F4/0 
genselect element add solid 1581/F1/0 
genselect element add solid 1863/F1/0 
genselect element add solid 1285/F1/0 
genselect element add solid 1619/F1/0 
genselect element add solid 1625/F4/0 
genselect element add solid 1970/F4/0 
genselect element add solid 1847/F1/0 
genselect element add solid 1250/F4/0 
genselect element add solid 1558/F1/0 
genselect element add solid 1572/F1/0 
genselect element add solid 1735/F1/0 
genselect element add solid 1722/F1/0 
genselect element add solid 1723/F1/0 
genselect element add solid 1716/F1/0 
genselect element add solid 1642/F1/0 
genselect element add solid 1424/F1/0 
pan 4.187001 49.074921;
genselect element add solid 1433/F1/0 
genselect element add solid 1427/F1/0 
genselect element add solid 1434/F1/0 
pan -1.542283 64.353058;
zoomhere 0.309384 -0.105114 0.409600;
zoomhere 0.309384 -0.105114 0.512000;
zoomhere 0.309384 -0.105114 0.640000;
zoomhere 0.309384 -0.105114 0.800000;
zoomhere 0.309384 -0.105114 1.000000;
genselect element add solid 1714/F1/0 
genselect element add solid 1712/F1/0 
genselect element add solid 1719/F1/0 
genselect element add solid 1720/F1/0 
genselect element add solid 1729/F1/0 
genselect element add solid 1894/F1/0 
genselect element add solid 1916/F1/0 
genselect element add solid 1229/F1/0 
genselect element add solid 1253/F1/0 
genselect element add solid 1305/F1/0 
genselect element add solid 1846/F1/0 
genselect element add solid 1709/F1/0 
genselect element add solid 1711/F1/0 
genselect element add solid 1724/F1/0 
genselect element add solid 1655/F1/0 
genselect element add solid 1918/F1/0 
genselect element add solid 1227/F1/0 
genselect element add solid 1486/F1/0 
genselect element add solid 1429/F1/0 
genselect element add solid 1440/F1/0 
genselect element add solid 1446/F1/0 
genselect element add solid 1428/F1/0 
genselect element add solid 1489/F1/0 
genselect element add solid 1647/F1/0 
genselect element add solid 1570/F1/0 
genselect element add solid 1727/F1/0 
genselect element add solid 1704/F1/0 
genselect element add solid 1708/F1/0 
genselect element add solid 1707/F1/0 
genselect element add solid 1705/F1/0 
genselect element add solid 1706/F1/0 
genselect element add solid 1702/F1/0 
genselect element add solid 1703/F1/0 
genselect element add solid 1701/F1/0 
genselect element add solid 1890/F1/0 
genselect element add solid 1890/F1/0 
genselect element add solid 1891/F1/0 
genselect element add solid 1885/F1/0 
genselect element add solid 1886/F1/0 
genselect element add solid 1661/F1/0 
genselect element add solid 1660/F1/0 
genselect element add solid 1256/F1/0 
genselect element add solid 1257/F1/0 
genselect element add solid 1449/F1/0 
genselect element add solid 1445/F1/0 
genselect element add solid 1448/F1/0 
genselect element add solid 1447/F1/0 
right
left
pan -15.205677 26.270622;
zoomhere 0.269795 -0.316761 1.250000;
zoomhere 0.269795 -0.316761 1.562500;
zoomhere 0.269795 -0.316761 1.250000;
zoomhere 0.269795 -0.316761 1.000000;
zoomhere 0.269795 -0.316761 0.800000;
zoomhere 0.269795 -0.316761 0.640000;
genselect element add solid 1791/F1/0 
genselect element add solid 1767/F1/0 
genselect element add solid 1303/F1/0 
genselect element add solid 1554/F4/0 
genselect element add solid 1577/F1/0 
genselect element add solid 1650/F1/0 
genselect element add solid 1752/F1/0 
genselect element add solid 1748/F1/0 
genselect element add solid 1552/F1/0 
pan 13.308151 56.657753;
genselect element add solid 1696/F1/0 
genselect element add solid 1695/F1/0 
genselect element add solid 1693/F1/0 
genselect element add solid 1777/F1/0 
genselect element add solid 1766/F1/0 
genselect element add solid 1785/F1/0 
pan -9.502886 101.749336;
genselect element add solid 1690/F1/0 
genselect element add solid 1689/F1/0 
genselect element add solid 1688/F1/0 
genselect element add solid 1771/F1/0 
genselect element add solid 1772/F1/0 
genselect element add solid 1773/F1/0 
genselect element add solid 1764/F1/0 
genselect element add solid 1762/F1/0 
genselect element add solid 1820/F1/0 
genselect element add solid 1872/F1/0 
center -182.794632 -57.267178 64.357391
pan 13.538033 22.417459;
pan 12.477055 16.582075;
genselect element add solid 1826/F1/0 
genselect element add solid 1849/F1/0 
genselect element add solid 1851/F1/0 
genselect element add solid 1848/F1/0 
genselect element add solid 1842/F1/0 
genselect element add solid 1817/F1/0 
genselect element add solid 1905/F1/0 
genselect element add solid 1904/F1/0 
genselect element add solid 1906/F1/0 
genselect element add solid 1910/F1/0 
genselect element add solid 1668/F1/0 
genselect element add solid 1909/F1/0 
genselect element add solid 1609/F1/0 
genselect element add solid 1608/F1/0 
genselect element add solid 1616/F1/0 
genselect element add solid 1613/F1/0 
genselect element add solid 1607/F1/0 
pan -68.121948 39.151596;
genselect element add solid 1606/F1/0 
genselect element add solid 1611/F1/0 
genselect element add solid 1605/F1/0 
genselect element add solid 1686/F1/0 
zoomhere 0.221408 -0.191761 0.512000;
zoomhere 0.221408 -0.191761 0.409600;
zoomhere 0.221408 -0.191761 0.512000;
zoomhere 0.221408 -0.191761 0.640000;
zoomhere 0.224340 -0.190341 0.800000;
zoomhere 0.224340 -0.190341 1.000000;
zoomhere 0.228739 -0.188920 1.250000;
zoomhere 0.228739 -0.188920 1.562500;
zoomhere 0.230205 -0.187500 1.953125;
zoomhere 0.230205 -0.187500 2.441406;
pan -81.299156 172.634109;
pan -76.240013 178.705063;
quat 0.786340 0.158343 0.397731 0.445429;
quat 0.687446 0.280637 0.631570 0.223113;
quat 0.475886 0.513515 0.711043 -0.065210;
quat 0.167672 0.562152 0.720594 -0.369617;
quat -0.149233 0.514967 0.591770 -0.601953;
quat -0.351599 0.416689 0.299777 -0.782867;
quat -0.594582 0.273868 0.074053 -0.752320;
quat -0.545471 0.027713 -0.359610 -0.756554;
elgenerate shell solidface 4 1973 
genselect clear
zoomhere 0.346041 -0.271307 3.051758;
pan -17.048042 227.019928;
quat -0.229577 -0.157427 -0.797378 -0.535443;
quat -0.207251 -0.444803 -0.805989 -0.331026;
elgenerate accept
genselect propagate off
genselect target part
selectpart select 1
selectpart on H2/0 
selectpart select 0
right
ac
zoomhere -0.033724 -0.018466 0.720000;
zoomhere -0.033724 -0.018466 0.900000;
zoomhere -0.033724 -0.018466 1.125000;
zoomhere -0.033724 -0.018466 1.406250;
zoomhere -0.033724 -0.018466 1.757813;
zoomhere -0.033724 -0.018466 1.406250;
elgenerate shelltype 2
genselect target segment
elgenerate shelltype 1
genselect target solid
genselect solid add part 2/0 
elgenerate shell solidsurface 5 2739
genselect clear
elgenerate accept
genselect target part
selectpart select 1
selectpart on S5/0 
selectpart select 0
elgenerate shelltype 1
genselect target solid
genselect target shell
genselect target shell
genselect propagate on
pan 2.611093 -7.405662;
quat -0.061350 0.779160 0.622608 0.038780;
genselect shell add shell 3590/0 
elgenerate solid shelldrag 6 3759 24 4 0 0 0 0 0 -27.0886 
genselect clear
elgenerate accept
genselect shell add shell 3420/0 
elgenerate solid shelldrag 7 4111 24 4 0 0 0 0 0 -27.0886 
genselect clear
elgenerate accept
Nid#     223, xyz=-114.4990845,30.06236267,-105.3602142
Nid#      94, xyz=-115.755127,30.06236267,-129.3273163
genselect shell add shell 3025/0 
elgenerate solid shelldrag 8 4463 24 4 0 0 0 -1.35443 0 -27.0886 
genselect clear
elgenerate accept
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
elgenerate solid saveset1
genselect target node
genselect propagate off
genselect target node
center -97.735168 29.343872 -100.230560
pan -6.392766 3.286410;
quat 0.068132 0.644762 0.737000 -0.190974;
pan -13.427021 -0.371405;
quat -0.023434 0.719714 0.693578 0.020308;
quat -0.205794 0.786816 0.580206 0.043937;
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 2
genselect propagate on
genselect propagate off
elgenerate solid saveset2
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect shell add proximity in S5/0  2.60886 
genselect propagate off
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect shell add proximity in S5/0  2.60886 
genselect shell add proximity in S5/0  2.60886 
zoomhere 0.105572 -0.008523 1.757813;
zoomhere 0.105572 -0.008523 2.197266;
zoomhere 0.105572 -0.008523 2.746583;
zoomhere 0.105572 -0.008523 2.197266;
zoomhere 0.105572 -0.008523 1.757813;
zoomhere 0.105572 -0.008523 1.406250;
zoomhere 0.105572 -0.008523 1.125000;
zoomhere 0.105572 -0.008523 0.900000;
zoomhere 0.105572 -0.008523 0.720000;
zoomhere 0.105572 -0.008523 0.576000;
zoomhere 0.105572 -0.008523 0.460800;
zoomhere 0.105572 -0.008523 0.576000;
genselect shell add proximity in S5/0  2.60886 
genselect propagate off
-M 8
+M 8
+M 3
-M 3
+M 4
-M 4
-M 5
+M 5
-M 6
+M 6
-M 7
+M 7
-M 8
+M 8
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
elgenerate shelltype 1
genselect target solid
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect target shell
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect shell add proximity in S5/0  2.60886 
elgenerate solid saveset1
genselect target node
genselect propagate off
genselect target node
pan -2.618782 3.818056;
quat 0.189388 0.674541 0.698302 -0.146629;
quat 0.270436 0.570131 0.748251 -0.204781;
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 2
genselect propagate on
genselect propagate off
quat 0.032503 0.867950 0.480247 0.122350;
clearid part
elgenerate solid saveset2
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect shell add proximity in S5/0  2.60886 
elgenerate solid saveset1
genselect target node
genselect propagate off
right
zoomhere 0.148094 -0.259943 0.460800;
zoomhere 0.148094 -0.259943 0.576000;
zoomhere 0.148094 -0.259943 0.720000;
zoomhere 0.148094 -0.259943 0.900000;
zoomhere 0.148094 -0.259943 1.125000;
zoomhere 0.148094 -0.259943 1.406250;
zoomhere -0.014663 -0.257102 1.125000;
zoomhere -0.016129 -0.257102 1.406250;
zoomhere -0.129032 -0.230114 1.125000;
zoomhere -0.129032 -0.230114 0.900000;
quat -0.051138 0.748248 0.661395 0.008201;
quat -0.129168 0.793058 0.591151 0.070107;
genselect node add proximity in S5/0  2.60886 
genselect node add proximity in  2.60886 
genselect node add proximity in S5/0  2.60886 
genselect clear
genselect propagate off
genselect target shell
elgenerate solid reselect 1
genselect propagate on
genselect propagate off
genselect shell add part 5/0 
saveproject "Tutorial_2-4" "C:\Naudé\University\Masters Project\Models\LS-PrePost_Tutorials\Tutorial_2-4.proj"
Save Config. parameters to file C:\Users\Naude Conradie\AppData\Roaming\LSTC\LS-PrePost4.6\lsppconf
