| Created by Marc Mentat 2019 (64bit)
*prog_option compatibility:prog_version:ment2019
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\naude conradie\desktop\repository\masters-project\models\marcmentat\units\grid_1_5x5\grid_4_f3d5e57c920ed3db3110604255fb421a\grid_4_f3d5e57c920ed3db3110604255fb421a.mud"
*fill_view
*edit_job job

*update_job
*submit_job 1 *monitor_job
